import time
from typing import List, Optional, Any


def _safe_str(value) -> str:
    if isinstance(value, str):
        return value
    return ""


class RecorderSession:
    """In-memory recording session. Per-device, per-session."""

    # Subclasses override this for platform-specific automationName
    AUTOMATION_NAME = "Appium"

    def __init__(self):
        self.steps: List[dict] = []

    def add_step(self, action: str, node_id: str, locator: dict, value: Any = None):
        self.steps.append({
            "action": action,
            "nodeId": node_id,
            "locator": locator,
            "value": value,
            "timestamp": time.time()
        })

    def clear(self):
        self.steps = []

    def export(self, lang: str, platform: str) -> str:
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
        if lang == "python":
            return self._export_python(platform, timestamp)
        elif lang == "java":
            return self._export_java(platform, timestamp)
        elif lang == "javascript":
            return self._export_javascript(platform, timestamp)
        return ""

    def _export_python(self, platform: str, timestamp: str) -> str:
        lines = [
            "# Generated by InspectorPlus — Appium Test Recorder",
            f"# Platform: {platform} | Language: Python",
            f"# Recorded: {timestamp}",
            "",
            "from appium import webdriver",
            "from appium.webdriver.common.appiumby import AppiumBy",
            "import pytest",
            "",
            "",
            "class TestRecording:",
            "    def setup_method(self):",
            f'        caps = {{"platformName": "{platform}", "app": "your_app.apk", "automationName": "{self.AUTOMATION_NAME}"}}',
            "        self.driver = webdriver.Remote(\"http://localhost:4723\", caps)",
            "",
        ]
        for i, step in enumerate(self.steps, 1):
            code = self._step_to_python(step)
            lines.append(f"    def test_step_{i}(self):")
            lines.append(f"        {code}")
            lines.append("")
        lines.append("    def teardown_method(self):")
        lines.append("        self.driver.quit()")
        return "\n".join(lines)

    def _step_to_python(self, step: dict) -> str:
        action = step.get("action", "")
        locator = step.get("locator", {})
        value: Any = step.get("value")
        strategy = _safe_str(locator.get("strategy", ""))
        loc_value = _safe_str(locator.get("value", ""))
        if action == "click":
            return f'self.driver.find_element(AppiumBy.{strategy}("{loc_value}")).click()'
        elif action == "fill":
            return f'self.driver.find_element(AppiumBy.{strategy}("{loc_value}")).send_keys("{value}")'
        elif action == "swipe":
            return f'self.driver.execute_script("mobile: swipe", {{\'startX\': {value.get("startX", 0)}, \'startY\': {value.get("startY", 0)}, \'endX\': {value.get("endX", 0)}, \'endY\': {value.get("endY", 0)}, \'speed\': 5000}})' if isinstance(value, dict) else "// swipe"
        elif action == "wait":
            return f"import time; time.sleep({value or 1})"
        return "pass"

    def _export_java(self, platform: str, timestamp: str) -> str:
        lines = [
            "// Generated by InspectorPlus — Appium Test Recorder",
            f"// Platform: {platform} | Language: Java",
            f"// Recorded: {timestamp}",
            "",
            "import org.openqa.selenium.By;",
            "import org.openqa.selenium.WebElement;",
            "import org.openqa.selenium.remote.DesiredCapabilities;",
            "import org.openqa.selenium.remote.RemoteWebDriver;",
            "import org.testng.annotations.*;",
            "",
            "public class TestRecording {",
            "    private RemoteWebDriver driver;",
            "",
            "    @BeforeMethod",
            "    public void setUp() {",
            "        DesiredCapabilities caps = new DesiredCapabilities();",
            f'        caps.setCapability("platformName", "{platform}");',
            "        caps.setCapability(\"app\", \"your_app.apk\");",
            f'        caps.setCapability("automationName", "{self.AUTOMATION_NAME}");',
            "        driver = new RemoteWebDriver(new URL(\"http://localhost:4723\"), caps);",
            "    }",
            "",
        ]
        for i, step in enumerate(self.steps, 1):
            code = self._step_to_java(step)
            lines.append(f"    @Test")
            lines.append(f"    public void testStep{i}() {{")
            lines.append(f"        {code}")
            lines.append("    }")
            lines.append("")
        lines.append("    @AfterMethod")
        lines.append("    public void tearDown() {")
        lines.append("        driver.quit();")
        lines.append("    }")
        lines.append("}")
        return "\n".join(lines)

    def _step_to_java(self, step: dict) -> str:
        action = step.get("action", "")
        locator = step.get("locator", {})
        value = step.get("value")
        strategy = _safe_str(locator.get("strategy", "")).upper()
        loc_value = _safe_str(locator.get("value", ""))
        by = "By.id" if strategy == "ID" else "By.xpath"
        if action == "click":
            return f'WebElement el = driver.findElement({by}("{loc_value}")); el.click();'
        elif action == "fill":
            return f'WebElement el = driver.findElement({by}("{loc_value}")); el.sendKeys("{value}");'
        elif action == "swipe":
            return f'// swipe from {value}'
        elif action == "wait":
            return f'Thread.sleep({(value or 1) * 1000});'
        return ""

    def _export_javascript(self, platform: str, timestamp: str) -> str:
        lines = [
            "// Generated by InspectorPlus — Appium Test Recorder",
            f"// Platform: {platform} | Language: JavaScript",
            f"// Recorded: {timestamp}",
            "",
            "const { remote } = require('webdriverio');",
            "",
            "async function runTest() {",
            "    const driver = await remote({",
            '        protocol: "http",',
            '        hostname: "localhost",',
            '        port: 4723,',
            f'        capabilities: {{ platformName: "{platform}", app: "your_app.apk", automationName: "{self.AUTOMATION_NAME}" }}',
            "    });",
            "",
        ]
        for i, step in enumerate(self.steps, 1):
            code = self._step_to_javascript(step)
            lines.append(f"    // Step {i}")
            lines.append(f"    await {code}")
            lines.append("")
        lines.append("    await driver.deleteSession();")
        lines.append("}")
        lines.append("runTest().catch(console.error);")
        return "\n".join(lines)

    def _step_to_javascript(self, step: dict) -> str:
        action = step.get("action", "")
        locator = step.get("locator", {})
        value = step.get("value")
        strategy = _safe_str(locator.get("strategy", ""))
        loc_value = _safe_str(locator.get("value", ""))
        by = f'`using: "xpath", value: "{loc_value}"`'
        if strategy == "id":
            by = f'`using: "id", value: "{loc_value}"`'
        elif strategy == "accessibility-id":
            by = f'`using: "accessibility id", value: "{loc_value}"`'
        if action == "click":
            return f'driver.$({{{by}}}).click()'
        elif action == "fill":
            return f'driver.$({{{by}}}).setValue("{value}")'
        elif action == "swipe":
            return '// swipe'
        elif action == "wait":
            return f'driver.pause({(value or 1) * 1000})'
        return "driver.pause(1000)"


class AndroidRecorderSession(RecorderSession):
    AUTOMATION_NAME = "UiAutomator2"


class IOSRecorderSession(RecorderSession):
    AUTOMATION_NAME = "XCUITest"