"""
Tests for RecorderSession export logic (python, java, javascript).
"""

import pytest
import time

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from device.android_bridge import RecorderSession


def make_step(action, locator_value, value=None):
    return {
        "action": action,
        "nodeId": "node1",
        "locator": {"strategy": "id", "value": locator_value},
        "value": value,
    }


class TestRecorderSessionAddStep:
    def test_add_step_appends_to_steps(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        assert len(session.steps) == 1
        assert session.steps[0]["action"] == "click"
        assert session.steps[0]["timestamp"] > 0


class TestRecorderSessionClear:
    def test_clear_resets_steps(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        session.clear()
        assert session.steps == []


class TestRecorderSessionExport:
    def test_export_empty_session(self):
        session = RecorderSession()
        # Empty session still generates header, but no test methods
        output = session.export("python", "android")
        assert "# Generated by InspectorPlus" in output
        # No test steps = no test methods
        assert "def test_step_1" not in output

    def test_export_unsupported_lang(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        assert session.export("ruby", "android") == ""


class TestRecorderSessionExportPython:
    def test_generates_python_class(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        output = session.export("python", "android")
        assert "from appium import webdriver" in output
        assert "class TestRecording" in output
        assert "def test_step_1" in output

    def test_python_click_step(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        output = session.export("python", "android")
        assert '.find_element(AppiumBy.id("btn")).click()' in output

    def test_python_fill_step(self):
        session = RecorderSession()
        session.add_step("fill", "node1", {"strategy": "text", "value": "username"}, "john")
        output = session.export("python", "android")
        assert 'send_keys("john")' in output

    def test_python_swipe_step(self):
        session = RecorderSession()
        session.add_step("swipe", "node1", {"strategy": "class_index", "value": "RecyclerView[0]"},
                         {"startX": 100, "startY": 200, "endX": 300, "endY": 400})
        output = session.export("python", "android")
        assert "mobile: swipe" in output
        assert "startX" in output

    def test_python_wait_step(self):
        session = RecorderSession()
        session.add_step("wait", "node1", {"strategy": "id", "value": "loading"}, "5")
        output = session.export("python", "android")
        assert "time.sleep(5)" in output

    def test_python_teardown(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        output = session.export("python", "android")
        assert "def teardown_method" in output
        assert "self.driver.quit()" in output


class TestRecorderSessionExportJava:
    def test_generates_java_class(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        output = session.export("java", "android")
        assert "public class TestRecording" in output
        assert "@BeforeMethod" in output
        assert "@AfterMethod" in output

    def test_java_click_step(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        output = session.export("java", "android")
        assert 'By.id("btn")' in output
        assert ".click()" in output

    def test_java_fill_step(self):
        session = RecorderSession()
        session.add_step("fill", "node1", {"strategy": "xpath", "value": "//input"}, "hello")
        output = session.export("java", "android")
        assert "sendKeys" in output
        assert "hello" in output

    def test_java_wait_step(self):
        session = RecorderSession()
        session.add_step("wait", "node1", {"strategy": "id", "value": "loading"}, "3")
        output = session.export("java", "android")
        assert "Thread.sleep" in output


class TestRecorderSessionExportJavaScript:
    def test_generates_javascript(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        output = session.export("javascript", "android")
        assert "webdriverio" in output
        assert "async function runTest" in output

    def test_javascript_click_with_id(self):
        session = RecorderSession()
        session.add_step("click", "node1", {"strategy": "id", "value": "btn"}, None)
        output = session.export("javascript", "android")
        assert 'using: "id"' in output
        assert "click()" in output

    def test_javascript_fill(self):
        session = RecorderSession()
        session.add_step("fill", "node1", {"strategy": "accessibility-id", "value": "username"}, "john")
        output = session.export("javascript", "android")
        assert "setValue" in output
        assert "john" in output

    def test_javascript_wait(self):
        session = RecorderSession()
        session.add_step("wait", "node1", {"strategy": "id", "value": "loading"}, "2")
        output = session.export("javascript", "android")
        assert "driver.pause" in output


class TestRecorderSessionStepToCode:
    def test_handles_non_string_strategy(self):
        from unittest.mock import MagicMock
        session = RecorderSession()
        # _step_to_python is called internally by export
        session.add_step("click", "node1", {"strategy": MagicMock(), "value": "btn"}, None)
        output = session.export("python", "android")
        # Should not crash and should produce valid python
        assert "find_element" in output
